-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public.move_vs_type
(
    move_id integer NOT NULL,
    type_id integer NOT NULL,
    ratio integer,
    CONSTRAINT move_vs_type_pkey PRIMARY KEY (move_id, type_id)
);

CREATE TABLE IF NOT EXISTS public.move_xref
(
    pokedex_entry integer NOT NULL,
    move_id integer NOT NULL,
    CONSTRAINT move_xref_pkey PRIMARY KEY (pokedex_entry, move_id)
);

CREATE TABLE IF NOT EXISTS public.my_poke_moves
(
    my_poke_id integer NOT NULL,
    move_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.my_pokemon
(
    id SERIAL,
    pokedex_entry integer NOT NULL,
    nickname character varying(20) COLLATE pg_catalog."default",
    hp integer NOT NULL,
    poke_lvl integer NOT NULL,
    CONSTRAINT my_pokemon_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.poke_move
(
    id SERIAL,
    move_name character varying(25) COLLATE pg_catalog."default",
    CONSTRAINT poke_move_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.poke_party
(
    trainer_id integer NOT NULL,
    my_poke_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.poke_trainer
(
    id SERIAL,
    trainer_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT poke_trainer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.poke_type
(
    id SERIAL,
    poke_type_name character varying(12) COLLATE pg_catalog."default",
    CONSTRAINT poke_type_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pokemon
(
    poke_name character varying(15) COLLATE pg_catalog."default",
    height_meters numeric(4, 1),
    weight_kg numeric(4, 1),
    poke_type1_id integer NOT NULL,
    poke_type2_id integer,
    pokedex_entry integer NOT NULL,
    CONSTRAINT pokemon_pkey PRIMARY KEY (pokedex_entry)
);

ALTER TABLE IF EXISTS public.move_vs_type
    ADD CONSTRAINT move_vs_type_move_id_fkey FOREIGN KEY (move_id)
    REFERENCES public.poke_move (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.move_vs_type
    ADD CONSTRAINT move_vs_type_type_id_fkey FOREIGN KEY (type_id)
    REFERENCES public.poke_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.move_xref
    ADD CONSTRAINT move_xref_move_id_fkey FOREIGN KEY (move_id)
    REFERENCES public.poke_move (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.move_xref
    ADD CONSTRAINT move_xref_pokedex_entry_fkey FOREIGN KEY (pokedex_entry)
    REFERENCES public.pokemon (pokedex_entry) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.my_poke_moves
    ADD CONSTRAINT my_poke_moves_move_id_fkey FOREIGN KEY (move_id)
    REFERENCES public.poke_move (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.my_poke_moves
    ADD CONSTRAINT my_poke_moves_my_poke_id_fkey FOREIGN KEY (my_poke_id)
    REFERENCES public.my_pokemon (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.my_pokemon
    ADD CONSTRAINT my_pokemon_pokedex_entry_fkey FOREIGN KEY (pokedex_entry)
    REFERENCES public.pokemon (pokedex_entry) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.poke_party
    ADD CONSTRAINT poke_party_my_poke_id_fkey FOREIGN KEY (my_poke_id)
    REFERENCES public.my_pokemon (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS const_my_poke_id
    ON public.poke_party(my_poke_id);


ALTER TABLE IF EXISTS public.poke_party
    ADD CONSTRAINT poke_party_trainer_id_fkey FOREIGN KEY (trainer_id)
    REFERENCES public.poke_trainer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pokemon
    ADD CONSTRAINT pokemon_poke_type1_id_fkey FOREIGN KEY (poke_type1_id)
    REFERENCES public.poke_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pokemon
    ADD CONSTRAINT pokemon_poke_type2_id_fkey FOREIGN KEY (poke_type2_id)
    REFERENCES public.poke_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;