SELECT * FROM pokemon;
SELECT * FROM poke_type;
SELECT * FROM poke_party;
SELECT * FROM poke_trainer;
SELECT * FROM poke_move;
SELECT * FROM my_pokemon;
SELECT * FROM my_poke_moves;
SELECT * FROM move_xref;
SELECT * FROM move_vs_type;